import type { FactCheckRecord } from "./types";

// Minimal PDF 1.4 generator — no deps. A4 (595×842), Helvetica/Helvetica-Bold.

function escapeText(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[\r\n]+/g, " ")
    .split("")
    .map((ch) => {
      const code = ch.charCodeAt(0);
      if (code < 32 || code > 126) return "?";
      return ch;
    })
    .join("");
}

function wrap(value: string, maxChars: number): string[] {
  const words = value.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length <= maxChars) current = candidate;
    else {
      if (current) lines.push(current);
      current = word.length > maxChars ? word.slice(0, maxChars) : word;
    }
  }
  if (current) lines.push(current);
  return lines.length > 0 ? lines : [""];
}

function buildPdf(record: FactCheckRecord): string {
  const W = 595;
  const H = 842;
  const LEFT = 44;
  const RIGHT = 44;
  const MAX_LINE = 82;

  const lines: Array<{ text: string; size: number; bold: boolean; gap: number }> = [];

  function heading(text: string) {
    lines.push({ text, size: 9, bold: true, gap: 5 });
  }
  function body(text: string) {
    lines.push({ text, size: 10, bold: false, gap: 4 });
  }
  function spacer(gap: number) {
    lines.push({ text: "__SPACER__", size: 1, bold: false, gap });
  }

  const verdictColor: Record<string, string> = {
    TRUE: "(0.00 0.90 0.63 rg)",
    FALSE: "(1.00 0.27 0.27 rg)",
    MISLEADING: "(0.96 0.65 0.14 rg)",
    UNVERIFIABLE: "(0.29 0.33 0.41 rg)",
  };

  // Title
  lines.push({ text: "TruthLock — Verdict Report", size: 18, bold: true, gap: 8 });
  body("On-chain fact check · GenLayer Intelligent Contract");
  spacer(14);

  heading("Claim");
  wrap(record.claim ? `"${record.claim}"` : "", MAX_LINE).forEach((l) => body(l));
  spacer(10);

  heading("Verdict");
  lines.push({
    text: `__VERDICT__${record.verdict}__CONF__${record.confidence}% confidence`,
    size: 13,
    bold: true,
    gap: 8,
  });
  spacer(8);

  heading("Explanation");
  wrap(record.explanation || "—", MAX_LINE).forEach((l) => body(l));
  spacer(10);

  heading("Sources checked");
  const sources = [record.source_url, ...record.sources_checked.filter((s) => s !== record.source_url)];
  sources.forEach((url, index) => {
    wrap(`${index + 1}. ${url}`, MAX_LINE).forEach((l) => body(l));
  });
  spacer(10);

  heading("Metadata");
  body(`Check ID: ${record.id}`);
  body(`Submitted: ${new Date(record.timestamp * 1000).toISOString()} (epoch ${record.timestamp})`);
  body(`Submitter: ${record.submitter}`);
  body(`Sources fetched: ${sources.length} · Block-timestamped on GenLayer`);
  spacer(22);

  body("Generated by TruthLock — consensus of validators, not opinions.");
  body("Share this report or verify on-chain: /result/" + record.id.slice(0, 12));

  // Build content stream
  let y = H - 64;
  const commands: string[] = [];

  function setFont(bold: boolean, size: number): void {
    commands.push(`/F${bold ? "B" : "1"} ${size} Tf`);
  }

  for (const entry of lines) {
    if (entry.text === "__SPACER__") {
      y -= entry.gap;
      continue;
    }

    // Verdict special line
    if (entry.text.startsWith("__VERDICT__")) {
      const match = /__VERDICT__(.*)__CONF__(.*)/.exec(entry.text);
      if (match) {
        const verdict = match[1];
        const conf = match[2];
        const color = verdictColor[verdict] ?? "(0.91 0.94 0.97 rg)";
        setFont(true, entry.size);
        // Position verdict word
        y -= entry.size + entry.gap;
        commands.push(`${LEFT} ${y} Td ${color} (${escapeText(verdict)}) Tj`);
        commands.push("ET");
        // Confidence inline continuation on same line offset — simpler: newline
        commands.push("BT");
        setFont(false, 10);
        y -= 14;
        commands.push(`${LEFT} ${y} Td 0 g (${escapeText(conf)}) Tj`);
        commands.push("ET");
        commands.push("BT");
        continue;
      }
    }

    setFont(entry.bold, entry.size);
    y -= entry.size + entry.gap;
    if (y < 48) break; // overflow guard — report fits one page for typical claim length
    commands.push(`${LEFT} ${y} Td 0 g (${escapeText(entry.text)}) Tj`);
    // Each Tj needs its own BT/ET pair; we use BT at start of each line and ET at end
    commands.push("ET");
    commands.push("BT");
  }

  // Wrap commands in a single BT ... ET block structure
  // First BT is opened implicitly; ensure we close trailing BT
  const streamContent =
    "BT\n" +
    commands.join("\n") +
    "\nET\n" +
    // Footer line
    `1 0.2 0.3 RG 0.5 w ${LEFT} 42 m ${W - RIGHT} 42 l S\n`;

  const streamBytes = new TextEncoder().encode(streamContent).length;

  const objects: string[] = [];
  objects.push("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
  objects.push("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
  objects.push(
    `3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 4 0 R /FB 5 0 R >> >> /Contents 6 0 R >>\nendobj\n`
  );
  objects.push("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");
  objects.push("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n");
  objects.push(`6 0 obj\n<< /Length ${streamBytes} >>\nstream\n${streamContent}endstream\nendobj\n`);

  let pdf = "%PDF-1.4\n%TruthLock\n";
  const offsets: number[] = [];
  let cursor = pdf.length;
  for (const obj of objects) {
    offsets.push(cursor);
    pdf += obj;
    cursor += obj.length;
  }
  const xrefPos = cursor;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;

  return pdf;
}

export function generateVerdictPdf(record: FactCheckRecord): Blob {
  const pdfString = buildPdf(record);
  const bytes = new TextEncoder().encode(pdfString);
  return new Blob([bytes], { type: "application/pdf" });
}

export function downloadVerdictPdf(record: FactCheckRecord): void {
  const blob = generateVerdictPdf(record);
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `truthlock-report-${record.id.slice(0, 8)}.pdf`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
